version: '3.1'
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: administrador
      WORDPRESS_DB_PASSWORD: contraseña
      WORDPRESS_DB_NAME: nombredb
    volumes:
      - wordpress:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: nombredb
      MYSQL_USER: administrador
      MYSQL_PASSWORD: contraseña
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.rourters.wp-secure.entrypoints=websecure"
      - "traefik.http.rourters.wp-secure.rules=Host(`api.dom.com`)"
volumes:
  wordpress:
  db:

networks:
  proxy:
    external: true
